version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-26-alpha
    environment:
      JVM_OPTS: -Xmx3200m
      KEYSTORE: /home/circleci/keystore.jks
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: |
            echo ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Retrieve keystore
          command: |
            sudo curl -L ${KEYSTORE_URI} > ${KEYSTORE}
      - run:
          name: Setup Google Services Json
          command: |
            echo "Setting up google services json files"
            mkdir -p /home/circleci/code/app/src/dev/debug/
            mkdir -p /home/circleci/code/app/src/staging/debug/
            mkdir -p /home/circleci/code/app/src/live/debug/
            mkdir -p /home/circleci/code/app/src/dev/release/
            mkdir -p /home/circleci/code/app/src/staging/release/
            mkdir -p /home/circleci/code/app/src/live/release/
            echo $GOOGLE_SERVICES_DEBUG | base64 --decode --ignore-garbage > /home/circleci/code/app/src/dev/debug/google-services.json
            echo $GOOGLE_SERVICES_RELEASE | base64 --decode --ignore-garbage > /home/circleci/code/app/src/staging/debug/google-services.json
            echo $GOOGLE_SERVICES_RELEASE | base64 --decode --ignore-garbage > /home/circleci/code/app/src/live/debug/google-services.json
            echo $GOOGLE_SERVICES_DEBUG | base64 --decode --ignore-garbage > /home/circleci/code/app/src/dev/release/google-services.json
            echo $GOOGLE_SERVICES_RELEASE | base64 --decode --ignore-garbage > /home/circleci/code/app/src/staging/release/google-services.json
            echo $GOOGLE_SERVICES_RELEASE | base64 --decode --ignore-garbage > /home/circleci/code/app/src/live/release/google-services.json
            echo "All Done!"
      - run:
          name: Run Tests
          command: |
            if [ "${CIRCLE_BRANCH}" == "develop" ]
            then
              ./gradlew lintDevRelease test
            elif [ "${CIRCLE_BRANCH}" == "master" ]
            then
              rtagx="release-.*"
              if [[ "${CIRCLE_TAG}" =~  $rtagx ]]
              then
                ./gradlew lintLiveRelease test
              else
                ./gradlew lintStagingRelease test
              fi
            fi
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
      - run:
          name: Build Target
          command: |
            if [ "${CIRCLE_BRANCH}" == "develop" ]
            then
              echo "Building Dev Release Build"
              ./gradlew assembleDevRelease
            elif [ "${CIRCLE_BRANCH}" == "master" ]
            then
              rtagx="release-.*"
              if [[ "${CIRCLE_TAG}" =~  $rtagx ]]
              then
                echo "Building Live Release Build"
                ./gradlew assembleLiveRelease
              else
                echo "Building Stage Release Build"
                ./gradlew assembleStagingRelease
              fi
            fi
      - deploy:
          name: Deploying Build
          command: |
            gitCommitMessage=\"$(git log --pretty=tformat:"%s | %cr" -n 1 $CIRCLE_SHA1)\"
            sleep 5
            if [ "${CIRCLE_BRANCH}" == "develop" ]
            then
              ipa="@app/build/outputs/apk/app-dev-release.apk"
            elif [ "${CIRCLE_BRANCH}" == "master" ]
            then
              rtagx="release-.*"
              if [[ "${CIRCLE_TAG}" =~  $rtagx ]]
              then
                ipa="@app/build/outputs/apk/app-live-release.apk"
              else
                ipa="@app/build/outputs/apk/app-staging-release.apk"
              fi
            fi

            if [ $ipa ]
            then
              curl \
                -F "status=2" \
                -F "notify=1" \
                -F "notes=$gitCommitMessage" \
                -F "notes_type=0" \
                -F "ipa=$ipa" \
                -H "X-HockeyAppToken: ${HOCKEY_TOKEN}" \
                https://rink.hockeyapp.net/api/2/apps/upload
            else
              echo "Something went wrong... no builds uploaded!"
            fi